### ISSUE TITLE
Little OT

### ISSUE THREAD

**Issue by pbosetti** [citolen/goproh4#10]
Hi,
I'd like to port your library to Ruby, and I'm just having some difficulty in figuring out what is the live streaming URL of the GP4, and what is the intended command sequence for enabling it.
Could you please disclose it?

Thanks,
Paolo

**Comment by citolen** [comment]
Hi Paolo,

Great that you are porting it !

Here are the three links to interact with the streaming feature of the GoPro:
http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=start
http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=restart
http://10.5.5.9/gp/gpControl/execute?p1=gpStream&c1=stop

Do a GET on those URLs to do the different actions start/restart/stop.
When you start/restart the stream the GoPro live stream will be available through the UDP protocol on port 8554.
However the GoPro will close the stream after a few seconds if you don't tell the GoPro to not close it.
This is why you need to regularly send the message "\_GPHD\_:0:0:2:0.000000\n" to the GoPro through UDP on port 8554.

Hope this can help you, feel free to ask me more information if needed.

Cheers,
Nils

**Comment by pbosetti** [comment]
Thanks! I'll keep you updated!
P
