### ISSUE TITLE
Semi-Gibberish displayed video (screenshot attached)

### ISSUE THREAD

**Issue by saket424** [citolen/goproh4#18]
![screenshot from 2016-05-31 14-07-47](https://cloud.githubusercontent.com/assets/4466507/15687216/26cc4b88-2739-11e6-879c-0a1c7c5ad708.png)

I am seeing semi-gibberish(pieces are broken but inividually do contain various parts of the video feed) when I browse at http://127.0..0.1:8082/index. what am i doing wrong -- seems like some error in the encoder/decoder cycle ?

**Comment by citolen** [comment]
Hey,

It seems like this issue #11, could you try changing the width and height variable (line 13,14) in [livestream.js](https://github.com/citolen/goproh4/blob/master/examples/livestream/livestream.js) ?

Try with the value 432x240.

If that works could you tell me which gopro you are using and which firmware version ?

**Comment by saket424** [comment]
Yes value 432x240 fixed it. Sorry for the duplicate

If that works could you tell me which gopro you are using and which firmware version ?

GoProH4 Black firmware version 3.0.0

**Comment by karjri** [comment]
Using value 432x240 fixes the problem also for me. Thank you!

Camera: GoPro HERO 4 Silver
Firmware: 03.00.00

Server: Raspbian 4.9.2-10 @ ffmpeg version N-80976-g9157ac2

**Comment by ahnl** [comment]
If above values don't work, use resolution 640x480

Works for GoPro HERO 7 Silver
