### ISSUE TITLE
MAC Address Wake Up Lan

### ISSUE THREAD

**Issue by driesvancraen** [citolen/goproh4#3]
Hello,

I was wondering in what format the MAC address needs to be in the camera object.
```
cams[0] = new GoPro.Camera({
    ip: '192.168.2.2',
    broadcastip: '192.168.2.255',
    //mac: '2122172514413965'
});
```
When I log the cam._mac I get [ 212, 217, 25, 144, 139, 65 ]

Awesome repo!

**Comment by citolen** [comment]
Hello,

The mac address is a serie of 6 bytes. The gopro camera sends it via http://yourcameraip/gp/gpControl. It looks like this "d4d9192e7276", the 6 bytes are encoded in hexadecimal. To send it in the UDP packet to wakeup the gopro it needs to be parsed as integers, this is why you get an array of 6 integers.

So to answer your questions it needs to be an array of 6 integers.

I hope this can help you.
