### ISSUE TITLE
Is this going to work with a GoPro Hero (1)?

### ISSUE THREAD

**Issue by paultrial** [citolen/goproh4#5]
Hello!

I'm trying to use your library to connect to a GoPro Hero. I think it's the first edition.

this is the code i've copied from one of your examples:
var GoPro = require ('goproh4');
var cam = new GoPro.Camera();
cam.status().then(function (status) {
    console.log('[status] = ', status);
});

this is the output:
Potentially unhandled rejection [1] Error: connect ETIMEDOUT 10.5.5.9:80
    at Object.exports._errnoException (util.js:874:11)
    at exports._exceptionWithHostPort (util.js:897:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1063:14)

Can it be done? Can I connect to my camera?
Thanks!

**Comment by citolen** [comment]
Hello Paul,

I didn't test for any other GoPro than the Hero 4 but I can confirm you that it isn't compatible with any previous version.

Could you confirm which version do you have because the first edition doesn't have wifi so there is no chance connecting to it.
When did you buy it ?
